name: testing aja

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: echo "Testing successful!"
        
      - name: Say Hi!
        run: echo "Hi, this is a test workflow!"
